//to make this a server component, layout code has been split.
import Layout from "@/components/common/Layout.jsx";
import "./globals.css";

//Meta-data for better SEO
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1"
        ></meta>
      </head>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
